app:
  title: Developer Hub
  baseUrl: http://localhost:3003
organization:
  name: Developer Hub Organization
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
  cors:
    origin: http://localhost:3003
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  auth:
    dangerouslyDisableDefaultAuthPolicy: true
  database:
    client: better-sqlite3
    connection:
      directory: .
proxy:
  skipInvalidProxies: true
  endpoints: {}
techdocs:
  builder: external
integrations:
  github:
    - host: github.com
      # Configure your GitHub token here
      token: ${GITHUB_TOKEN}
auth:
  environment: development
  allowGuestAccess: true
  providers:
    guest:
      enabled: true
      dangerouslyAllowOutsideDevelopment: true
      userEntityRef: user:default/guest
catalog:
  rules:
    - allow: [Component, System, Group, Resource, Location, Template, API]
  locations:
    - type: file
      target: ./catalog-info.yaml


