apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frameportal
  title: frameportal Developer Hub
  description: framework portal
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/Joeyyubo/Framework-dev-portal
      title: Repository
      icon: github
      type: sourcecode
spec:
  type: service
  lifecycle: production
  owner: group:default/rhdh-team
